import Head from "next/head";
import Header from "./ui/Header";
import Modal from "react-modal";
import Pedidos from "./Pedidos";
import Login from "./Login";
import Register from "./Register";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { useAuth } from "../context/authContext";
//import Menu from "./Menu";

const customStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
  },
};

Modal.setAppElement("#__next");

const Layout = ({ children }) => {
  const { currentUser: user, modal, productoActual, opcLogin,opcRegister } = useAuth();
  return (
    <>
      <Head>
        <title>Kiosco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:flex ml-3">
        <aside className="md:w-4/12 xl:w-1/4 2xl:w-1/5">
          <Header />
        </aside>

        <main className="md:w-8/12 xl:w-3/4 2xl:w-4/5 h-screen overflow-y-scroll ">
          <div className="p-10">{children}</div>
        </main>
      </div>

      {modal && (
        <Modal isOpen={modal} style={customStyles}>
          <Pedidos producto={productoActual} />
        </Modal>
      )}

      {opcLogin && (
        <Modal isOpen={opcLogin} style={customStyles}>
          <Login />
        </Modal>
      )}

      {opcRegister && (
        <Modal isOpen={opcRegister} style={customStyles}>
          <Register />
        </Modal>
      )}

      <ToastContainer />
    </>
  );
};

export default Layout;
